/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb/Breadcrumb.vue')['default']
    BreadcrumbRouter: typeof import('./src/components/BreadcrumbRouter.vue')['default']
    BreadcrumbRouterRender: typeof import('./src/components/breadcrumb/BreadcrumbRouterRender.vue')['default']
    copy: typeof import('./src/components/icons/IconFont copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconFont: typeof import('./src/components/icons/IconFont.vue')['default']
    IconFontGithub: typeof import('./src/components/icons/IconFontGithub.vue')['default']
    IconFontGitHub: typeof import('./src/components/icons/IconFontGitHub.vue')['default']
    IconGitHub: typeof import('./src/components/icons/IconGitHub.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
